### ISSUE TITLE
help me I don't understand anything...

### ISSUE THREAD

**Issue by NelfiHacker** [Crevils/InstaReport#61]
I don't know how to code. all I want is to ban an account, can someone do it for free please?

**Comment by NelfiHacker** [comment]
$ python main.py -u shinakaa_ -f INSTAGRAM_ACCOUNTS_FILE.txt
Traceback (most recent call last):
  File "C:\Users\Tomat\instareport\main.py", line 8, in <module>
    from report_accounts import report_accounts
  File "C:\Users\Tomat\instareport\report_accounts.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium

**Comment by jeturgavli** [comment]
Hi, @NelfiHacker 

It looks like you're trying to run a Python script that uses Selenium, but you're encountering a ModuleNotFoundError because the selenium module is not installed on your pc.

go to your terminal : pip install selenium
